[project]
name = "mixcloud-lrc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mutagen>=1.47.0",
    "requests>=2.32.5",
    "yt-dlp>=2026.2.4",
]
